version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
    - "spec/"
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-71"
    config:
      file: .rubocop.yml
    checks:
      Rubocop/Rails/HasAndBelongsToMany:
        enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
- config/**
- db/**
- public/api/docs/**
