engines:
  rubocop:
    enabled: true
    channel: rubocop-0-69
    config:
      file: .rubocop.yml
  shellcheck:
    enabled: true
  eslint:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.coffee"
  - "**.sass"
  - "**.haml"
  - Gemfile.lock
exclude_paths:
- config/
- db/
- public/api/docs/
