sudo: required
language: ruby
cache:
  bundler: true
  yarn: true
services:
  - postgresql
  - elasticsearch

# Note: we will build pull requests, and these branches
# This stops travis running two jobs on every pull requests
branches:
  only:
  - master
  - staging

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - chromium-chromedriver
    - google-chrome-stable
env:
  global:
    - RAILS_ENV=test
before_install:
- ELASTIC_SEARCH_VERSION="6.2.3" ./bin/install_elasticsearch.sh
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- export PATH=$PWD/geckodriver:$PATH
before_script:
- bundle install
- yarn install
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rails assets:precompile
- bundle exec rails search:index
- export PERCY_TARGET_BRANCH=$TRAVIS_BRANCH
- export PERCY_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
script:
- npx percy exec -- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id $CC_TEST_REPORTER_ID"
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    repo: ServiceInnovationLab/feijoa
  app:
    master: feijoa
    staging: feijoa-staging
  run:
  - bundle install
  - yarn install
  - bundle exec rake tmp:cache:clear
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
  - restart
  api_key:
    secure: zXmt0xZpG6l6bVloshfBNmw2wbFiVOcsCVmGxpXh2LZqGfYQRJzra7SMOD9aShtc+Ue6OtL5NM0DogAIkiAHMV/AIMiecZoGWfYFAO+TEF5CL835aAc9/rjGy+D850RMxMu3Se29wTmGQEcwLuP9+SXXQUrcv33I32SCeqUH4a7dGcCxrnGXxS+T8v9PcexHJFLU6EuEW4i6XsWsbbHxqyUYbw/FU3WOs4FMmZW01JFioOttLbHw/z5ze5ALQZOmWb0quv2Tp2YIvN5bALa2q+csNp//dUzQoSl3zXInqfb9q5zQToptbwnyGde9/+XXsgvbnGktmyJ8oiSb586hxNDWnpuDT1Gtlp+VYkrmyZqCp9mWIX+5wmUazhJK7XeAih3Qro8t0v/k66jCfXUteef65YPI8MW//ZLdPQSjnt2ubbKZmEa0zNCcJXr84MMuoMjYtNaDwkke64DQdgxtAp0AjxL9uneTXt5F7NPfreGTEkYtRv0HWn4Zn79MUhCbv+oMHjZ9WXEwDpjSthE7HKClWQccArHuYWNsodAWfPsVqRJA+K04Ai9rV/5XpwJr9ySqTDgGQc+VIMLnAWuFksBOi4K36rL7UZV11QtQmu9001uYwgdCextRGPJInnbxAKZZREgLIVFQ8RE3O6vp7Vzj1XA7vJUsk3xG0X2SwMU=
