sudo: required
language: ruby
cache:
  bundler: true
  yarn: true
services:
  - postgresql
  - elasticsearch

# Note: we will build pull requests, and these branches
# This stops travis running two jobs on every pull requests
branches:
  only:
  - master
  - staging

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - chromium-chromedriver
    - google-chrome-stable
env:
  global:
    - RAILS_ENV=test
before_install:
- ELASTIC_SEARCH_VERSION="6.2.3" ./bin/install_elasticsearch.sh
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- export PATH=$PWD/geckodriver:$PATH
before_script:
- bundle install
- yarn install
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rails assets:precompile
- bundle exec rails search:index
- export PERCY_TARGET_BRANCH=$TRAVIS_BRANCH
- export PERCY_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
script:
- npx percy exec -- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id $CC_TEST_REPORTER_ID"
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    repo: ServiceInnovationLab/feijoa
  app:
    master: feijoa
    staging: feijoa-staging
  run:
  - bundle install
  - yarn install
  - bundle exec rake tmp:cache:clear
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
  - restart
  api_key:
    secure: O/q0OtCVYsSW3G7n4SzKQRVg0ZOCxx/8OM1QbhRRs9Vjl3Fs1VVbgHwGPibUNci0z4ciPPdAGlROBri+nlgvbgnCmhbEbqlZujQ0RVpUxtoB58rwJ8YhqYRnRu/cJC/5JeZL/mrOTYNT8aZ8Q11j65SFGBZTvcHYgXJLMeIP3+SpQ/o35jJun7HOciV0alrEFjD+Prrg95dJqI0OarcsvP0gqFRjeL1UzBvMYIjBKWuOnWvggsl6l/J0ofcGinOoqUpYYU5PbifIm41cES1rB1ko9Cx/dQ4gW9aXR1TvenZjQFv2jknUwQl6mUsEQb/gamKEZx0Xj0Y3KuVH1ZI6TScln/y3rRhmndmJHkpNtpx163G0kiMUEyxba/+o+hLsYNaeUNKbNtIgl4EX3dPyPf9O64OntgWA4LO4hJp5WS2BUPDIMC5ClUlc4fSsQQcfXeEEJD8sBGhCw34zTwAi2lsFkzKF9LXskShXT1sTNXJVFWXK9ThZpqem7G1bGzULzcrVZ7gddayRJRUcYZC+QAivTCnUKTEB3+2DF2vJcDdMcIdqQTD1wuNgU3cMi6hQlvtzELMWi27bP57BNY/06x3ZKZiUn53pzDi1UdFkZiBKEnYaxtpsrPUGyvQ9e3iB+qTuBf2He4q4IJ87MHdJ39FP9WoLxyQTnd5fUq+EI1c=
